### ISSUE TITLE
동영상 편집에 대한 의견

### ISSUE THREAD

**Issue by Albert-learner** [kookmin-sw/capstone-2020-14#1]
![KakaoTalk_20200508_163123503](https://user-images.githubusercontent.com/39715124/81382521-7d5b5880-9149-11ea-97d4-8f6b8a78ad19.gif)
동영상을 이런 식으로 원본 동영상 어느 지점에서 on버튼으로 눌렀을 때 그 지점에서 시작되게끔 싱크를 맞추려고 하는데 어떤가요??

**Comment by myunghakLee** [comment]
저희 영상은 하나이고 그 영상에 bounding box를 칠지 말지를 정하는 것이 on/off 버튼이니 싱크 문제는 없을 것으로 예상됩니다.(즉 영상이 1개밖에 없으니 싱크 문제는 존재하지 않을것 같습니다)
